server {
	listen 80 default_server;
	listen [::]:80 default_server;
    server_name chaire-paas.com www.chaire-paas.com;
    index index.html;

    location /.well-known/acme-challenge/ {
        root /var/www/html;
    }
    location / {
        return 301 https://$host$request_uri;
    }
}

server {
	server_name chaire-paas.com www.chaire-paas.com;

	access_log  /home/cyrilvincent/skema/web/nginx/linux/logs/host.access.log  main;
	error_log  /home/cyrilvincent/skema/web/nginx/linux/logs/host.error.log  error;

    root /home/cyrilvincent/skema/web/nginx/linux/html;

	index index.html;

    proxy_connect_timeout 10s;
    proxy_send_timeout 300s;
    proxy_read_timeout 300s;

    include /home/cyrilvincent/skema/web/nginx/linux/deny/deny.conf;

	location /api/ {
        proxy_pass http://127.0.0.1:8000/; # bien mettre le / à la fin
        # proxy_pass http://api_backend/;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Connection "";
        proxy_connect_timeout 10s;
        proxy_send_timeout 10s;
        proxy_read_timeout 300s;
        limit_req zone=api_limit burst=10 nodelay;
    }

	location / {
		try_files $uri $uri/ =404;
		limit_req zone=api_limit burst=20;
	}

	error_page  404              /404.html;
	error_page  500 502 503 504  /50x.html;

    listen [::]:443 ssl ipv6only=on; # managed by Certbot
    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/chaire-paas.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/chaire-paas.com/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot


}



# TODO
# systemd gunicorn
# certbot timer ok
# pkill gunicorn
# tmux new -s myapp
# python script.py
# tmux attach -t mya
# CTRL + B D
# ou
# nohup python script.py > logs/nohup.log 2>&1 &
# MEttre en place fail2ban

# sudo systemctl status certbot.timer


