server {

	listen 80 default_server; # default_server = fallback à enlever quand il y aura chaire_paas
	listen [::]:80 default_server; #IPv6
	server_name _; # Fallback

	access_log  /home/cyrilvincent/skema/web/nginx/linux/logs/host.access.log  main;
	error_log  /home/cyrilvincent/skema/web/nginx/linux/logs/host.access.log  error;

    # 	root /var/www/html;
    root /home/cyrilvincent/skema/web/nginx/linux/html;

	index index.html index.htm;

    proxy_connect_timeout 10s;
    proxy_send_timeout 300s;
    proxy_read_timeout 300s;

	location /api/ {
        proxy_pass http://127.0.0.1:8000/; # bien mettre le / à la fin
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Connection "";
        proxy_connect_timeout 10s;
        proxy_send_timeout 300s;
        proxy_read_timeout 300s;

    }

	location / {
		try_files $uri $uri/ / =404;
	}

	error_page  404              /404.html;
	error_page  500 502 503 504  /50x.html;
}

# TODO
# PG.conf
# SSL
# Redirection www
# MAJ CORS
# Gunicorn /!\ Timeout
# Logs
# DDoS limit_req* & limit_conn*
# Blocage user-agent
# fail2ban
# Server chaire-paas + fallback

	# SSL configuration
	#
	# listen 443 ssl default_server;
	# listen [::]:443 ssl default_server;
	#
	# Note: You should disable gzip for SSL traffic. TODO à demander à IA
	# See: https://bugs.debian.org/773332
	#
	# Read up on ssl_ciphers to ensure a secure configuration.
	# See: https://bugs.debian.org/765782
	#
	# Self signed certs generated by the ssl-cert package
	# Don't use them in a production server!
	#
	# include snippets/snakeoil.conf;

