name = "ICIP"
version = "3.1.0.alpha"
copyright = "(c) Skema 2021 - 2023"
adresse_path = "data/adresse"
connection_string = "postgresql://postgres:sa@localhost/icip"
ban_mean = 0.975
ban_std = 0.054
osm_nb_std = 1
tarif_datesource_back = 3
source_rpps_win_etab = 0.9
