# SHOW config_file;
# /etc/postgresql/17/main/postgresql.conf
# verif : sudo -u postgres psql -c "SELECT name, setting, error FROM pg_file_settings WHERE error IS NOT NULL;"
#  sudo pg_ctlcluster 17 main restart
# sudo -u postgres psql -c "
  # SELECT name, setting, unit, pending_restart
  # FROM pg_settings
  # WHERE name IN ('shared_buffers', 'max_worker_processes', 'autovacuum_max_workers');"
# -------- Mémoire --------
shared_buffers = 2GB # 25% RAM si server only
effective_cache_size = 8GB # 50 à 75%
work_mem = 16MB
maintenance_work_mem = 512MB

# -------- Connexions --------
max_connections = 100 # Peut monter à 300 avec work_mem=8 mais j'ai beaucoup de grosses requetes, si on augmente work_mem par 2 on divise par 2 max_connection

# -------- CPU --------
max_worker_processes = 4
max_parallel_workers = 4
max_parallel_workers_per_gather = 2
max_parallel_maintenance_workers = 1

# -------- WAL / Checkpoints --------
wal_buffers -1 # 16 pour copilot 64 pour claude
checkpoint_completion_target = 0.9
max_wal_size = 2GB
min_wal_size = 512MB

# -------- Autovacuum --------
autovacuum = on
autovacuum_max_workers = 1
autovacuum_naptime = 1min

# -------- SSD --------
random_page_cost = 1.1
effective_io_concurrency = 200