# SHOW config_file;
# /etc/postgresql/17/main/postgresql.conf
# -------- Mémoire --------
shared_buffers = 3GB
effective_cache_size = 9GB
work_mem = 16MB
maintenance_work_mem = 512MB

# -------- Connexions --------
max_connections = 80

# -------- CPU --------
max_worker_processes = 6
max_parallel_workers = 3
max_parallel_workers_per_gather = 2

# -------- WAL / Checkpoints --------
wal_buffers = 16MB
checkpoint_completion_target = 0.9
max_wal_size = 2GB
min_wal_size = 512MB

# -------- Autovacuum --------
autovacuum = on
autovacuum_max_workers = 1
autovacuum_naptime = 10s

# -------- SSD --------
random_page_cost = 1.1
effective_io_concurrency = 200