# sudo cp nginx.conf /etc/nginx/

user www-data;
worker_processes 4;
pid /run/nginx.pid;
error_log /var/log/nginx/error.log;
include /etc/nginx/modules-enabled/*.conf;

events {
	worker_connections 512;
}

http {
    include /home/cyrilvincent/skema/web/nginx/linux/conf/*.conf;
}


